print('Hello World')
myName = input("Whats your name?\n")
print("It is good to meet you, " + myName)
print('The length of your name is: ')
print(len(myName))
myAge = input("Whats age?\n")
print('you will be ' + str(int(myAge) + 1) + ' in a year.')
